server:
  port: 9000

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.190.224:8848
        cluster-name: FZ
        metadata:
          version: v1
    sentinel:
      transport:
        dashboard: 47.113.190.224:8858
        port: 8719
        client-ip: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.190.224/user_base?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 47.113.190.224
    port: 6379
    password: 123456
    timeout: 1000

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml


